spring.application.name=warehouse-management-system

server.servlet.context-path=/api/v1

#logging.pattern.console=%d{HH:mm:ss} %-5level %logger{20} - %msg%n

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc

# Assicurati di aver abilitato l'esportazione
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1
#spring.ai.ollama.chat.options.temperature=0.4