spring.application.name=warehouse-management-system

spring.datasource.url=jdbc:mariadb://localhost:3306/wms
spring.datasource.username=root
spring.datasource.password=louvre
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update