package com.relatech.warehouse_management_system.outbound.dto;

import com.relatech.warehouse_management_system.common.util.ErrorReason;
import com.relatech.warehouse_management_system.common.util.PickListItemState;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import lombok.*;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Represents a single item within a pick list.")
public class PickListItemDto {

    @Schema(description = "Unique identifier of the pick list item.", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Unique code generated by app of the pick list item.", accessMode = Schema.AccessMode.READ_ONLY)
    String code;

    @Schema(description = "SKU or product identifier.")
    private String productCode;

    @Schema(description = "PickListItem status", example = "OPEN")
    private PickListItemState state;

    @Schema(description = "Quantity to be picked.")
    @Min(value = 0, message = "Quantity must be greater than or equal to 0")
    private Integer quantity;

    @Schema(description = "Quantity picked.")
    @Min(value = 0, message = "Quantity must be greater than or equal to 0")
    private Integer pickedQty;

    @Schema(description = "Picking sequence number of slot where the product is stored.")
    private Integer pickingSequence;

    @Schema(description = "Reason for a picking discrepancy or issue.")
    private ErrorReason errorReason;

    @Schema(description = "Warehouse slot/location where the product is stored.")
    private String slotCode;

    @Schema(description = "Sales order code associated with this pick list item.")
    private String salesOrderCode;

    @Schema(description = "Line number of the sales order associated with this item.")
    private Integer salesOrderLineNumber;
}
