{
 "title": "loki based dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {app=\"$app\"} | json | unwrap Elapsed [$__auto]) by (RequestPath)",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({app=\"$app\"}[1m]))"
    }
   ]
  },
  {
   "title": "Top endpoints",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(\r\n 10,\r\n sum by (RequestPath)(\r\n  count_over_time(\r\n   {app=\"$app\"}\r\n   | json\r\n   | __error__!=\"JSONParserErr\"\r\n   #| SourceContext=\"Serilog.AspNetCore.RequestLoggingMiddleware\"\r\n  [5m])\r\n )\r\n)",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  }
 ]
}