{
 "title": "Unified WMS Dashboard",
 "description": "first dashboard example",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Trace Analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      {
       "id": "2b3ca22c",
       "operator": ">=",
       "scope": "span",
       "tag": "http.response.status_code",
       "value": [ "200" ]
      },
      {
       "id": "service-name",
       "operator": "=~",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "unknown_service:dotnet_Warehouse-Management-System",
        "$app"
       ]
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"$app\"} \r\n| json \r\n| RequestPath=~\"/api/v1/.*\""
    }
   ]
  },
  {
   "title": "Log Throughput per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "count_over_time(\r\n  {app=\"$app\"}\r\n  | json\r\n  #| __error__!=\"JSONParserErr\"\r\n  #|= \"INFO\"\r\n[1m])"
    }
   ]
  },
  {
   "title": "Top Endpoints by Request Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (RequestPath) (\r\n  count_over_time(\r\n    {app=\"$app\"}\r\n    | json\r\n  [5m])\r\n)"
    }
   ]
  }
 ]
}